// Settings mode
export const SET_MIN_VALUE = 'SETTINGS/SET-MIN-VALUE'
export const SET_MAX_VALUE = 'SETTINGS/SET-MAX-VALUE'
export const SAVE_SETTINGS = 'SETTINGS/SAVE-SETTINGS'
export const SET_ERROR_MESSAGE = 'SETTINGS/SET-ERROR-MESSAGE'

// Display mode
export const SET_INTERFACE_MODE = 'DISPLAY/SET-INTERFACE-MODE'
export const SET_COUNT = 'DISPLAY/SET-COUNT'
export const INCREMENT_COUNT = 'DISPLAY/INCREMENT-COUNT'
export const RESET_COUNT = 'DISPLAY/RESET-COUNT'

